#ifndef _EVENT_LIST_HPP
#define _EVENT_LIST_HPP

#define EVENT_TYPE_DEBUG_MESSAGE 1
#define EVENT_TYPE_LOGIN_REQUEST 100
#define EVENT_TYPE_LOGIN_CONFIRMATION 101
#define EVENT_TYPE_LOGIN_DENIED 102

#endif