#pragma once

#define EVENT_TYPE_DEBUG_MESSAGE 1

#define EVENT_TYPE_LOGIN_REQUEST 100
#define EVENT_TYPE_LOGIN_CONFIRMATION 101
#define EVENT_TYPE_LOGIN_DENIED 102

#define EVENT_TYPE_PLAYER_VELOCITY 2000
#define EVENT_TYPE_PLAYER_LOCATION 2001
#define EVENT_TYPE_SPAWN_NEW_PLAYER 2100
#define EVENT_TYPE_USER_INPUT 2200

#define EVENT_TYPE_GAMESTATE_PLAYERINPUT_HISTORY 2300